/*
 * This file is generated by jOOQ.
 */
package me.leslie.generals.server.persistence.jooq;


import me.leslie.generals.server.persistence.jooq.tables.Army;
import me.leslie.generals.server.persistence.jooq.tables.Troop;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONSTRAINT_INDEX_1 = Indexes0.CONSTRAINT_INDEX_1;
    public static final Index CONSTRAINT_INDEX_1E = Indexes0.CONSTRAINT_INDEX_1E;
    public static final Index CONSTRAINT_INDEX_1EC = Indexes0.CONSTRAINT_INDEX_1EC;
    public static final Index PRIMARY_KEY_1 = Indexes0.PRIMARY_KEY_1;
    public static final Index PRIMARY_KEY_4 = Indexes0.PRIMARY_KEY_4;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONSTRAINT_INDEX_1 = Internal.createIndex("CONSTRAINT_INDEX_1", Army.ARMY, new OrderField[]{Army.ARMY.HQ}, false);
        public static Index CONSTRAINT_INDEX_1E = Internal.createIndex("CONSTRAINT_INDEX_1E", Army.ARMY, new OrderField[]{Army.ARMY.TROOP}, false);
        public static Index CONSTRAINT_INDEX_1EC = Internal.createIndex("CONSTRAINT_INDEX_1EC", Army.ARMY, new OrderField[]{Army.ARMY.HQ, Army.ARMY.TROOP}, true);
        public static Index PRIMARY_KEY_1 = Internal.createIndex("PRIMARY_KEY_1", Army.ARMY, new OrderField[]{Army.ARMY.HQ, Army.ARMY.TROOP}, true);
        public static Index PRIMARY_KEY_4 = Internal.createIndex("PRIMARY_KEY_4", Troop.TROOP, new OrderField[]{Troop.TROOP.ID}, true);
    }
}
