/*
 * This file is generated by jOOQ.
 */
package me.leslie.generals.server.persistence.jooq;


import me.leslie.generals.server.persistence.jooq.tables.Army;
import me.leslie.generals.server.persistence.jooq.tables.Troop;
import me.leslie.generals.server.persistence.jooq.tables.records.ArmyRecord;
import me.leslie.generals.server.persistence.jooq.tables.records.TroopRecord;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code></code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TroopRecord, Integer> IDENTITY_TROOP = Identities0.IDENTITY_TROOP;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ArmyRecord> CONSTRAINT_1EC9 = UniqueKeys0.CONSTRAINT_1EC9;
    public static final UniqueKey<ArmyRecord> CONSTRAINT_1EC = UniqueKeys0.CONSTRAINT_1EC;
    public static final UniqueKey<TroopRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ArmyRecord, TroopRecord> CONSTRAINT_1 = ForeignKeys0.CONSTRAINT_1;
    public static final ForeignKey<ArmyRecord, TroopRecord> CONSTRAINT_1E = ForeignKeys0.CONSTRAINT_1E;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<TroopRecord, Integer> IDENTITY_TROOP = Internal.createIdentity(Troop.TROOP, Troop.TROOP.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ArmyRecord> CONSTRAINT_1EC9 = Internal.createUniqueKey(Army.ARMY, "CONSTRAINT_1EC9", Army.ARMY.HQ, Army.ARMY.TROOP);
        public static final UniqueKey<ArmyRecord> CONSTRAINT_1EC = Internal.createUniqueKey(Army.ARMY, "CONSTRAINT_1EC", Army.ARMY.HQ, Army.ARMY.TROOP);
        public static final UniqueKey<TroopRecord> CONSTRAINT_4 = Internal.createUniqueKey(Troop.TROOP, "CONSTRAINT_4", Troop.TROOP.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ArmyRecord, TroopRecord> CONSTRAINT_1 = Internal.createForeignKey(me.leslie.generals.server.persistence.jooq.Keys.CONSTRAINT_4, Army.ARMY, "CONSTRAINT_1", Army.ARMY.HQ);
        public static final ForeignKey<ArmyRecord, TroopRecord> CONSTRAINT_1E = Internal.createForeignKey(me.leslie.generals.server.persistence.jooq.Keys.CONSTRAINT_4, Army.ARMY, "CONSTRAINT_1E", Army.ARMY.TROOP);
    }
}
