/*
 * This file is generated by jOOQ.
 */
package me.leslie.generals.server.persistence.jooq;


import me.leslie.generals.server.persistence.jooq.tables.Army;
import me.leslie.generals.server.persistence.jooq.tables.Troop;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>ARMY</code>.
     */
    public static final Army ARMY = Army.ARMY;

    /**
     * The table <code>TROOP</code>.
     */
    public static final Troop TROOP = Troop.TROOP;
}
