/*
 * This file is generated by jOOQ.
 */
package me.leslie.generals.core.entity.interfaces;


import javax.annotation.processing.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public interface ITroop extends Serializable {

    /**
     * Getter for <code>TROOP.ID</code>.
     */
    public Integer getId();

    /**
     * Getter for <code>TROOP.CURRENT_HEALTH</code>.
     */
    public Integer getCurrentHealth();

    /**
     * Getter for <code>TROOP.MAX_HEALTH</code>.
     */
    public Integer getMaxHealth();

    /**
     * Getter for <code>TROOP.POS_X</code>.
     */
    public Double getPosX();

    /**
     * Getter for <code>TROOP.POS_Y</code>.
     */
    public Double getPosY();

    /**
     * Getter for <code>TROOP.NORMAL_SPEED</code>.
     */
    public Double getNormalSpeed();

    /**
     * Getter for <code>TROOP.STREET_SPEED</code>.
     */
    public Double getStreetSpeed();

    /**
     * Getter for <code>TROOP.DIFFICULT_TERRAIN_SPEED</code>.
     */
    public Double getDifficultTerrainSpeed();

    /**
     * Getter for <code>TROOP.CLOSE_COMBAT_RANGE</code>.
     */
    public Double getCloseCombatRange();

    /**
     * Getter for <code>TROOP.RANGED_COMBAT_RANGE</code>.
     */
    public Double getRangedCombatRange();

    /**
     * Getter for <code>TROOP.NORMAL_VIEW_DISTANCE</code>.
     */
    public Double getNormalViewDistance();

    /**
     * Getter for <code>TROOP.DISADVANTAGED_VIEW_DISTANCE</code>.
     */
    public Double getDisadvantagedViewDistance();

    /**
     * Getter for <code>TROOP.ADVANTAGED_VIEW_DISTANCE</code>.
     */
    public Double getAdvantagedViewDistance();

}
