/*
 * This file is generated by jOOQ.
 */
package me.leslie.generals.core.entity.pojos;


import me.leslie.generals.core.entity.interfaces.IArmy;
import org.apache.commons.lang3.builder.EqualsBuilder;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.2"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Army implements IArmy {

    private static final long serialVersionUID = -1008253768;

    private Integer hq;
    private Integer troop;

    public Army() {
    }

    public Army(IArmy value) {
        this.hq = value.getHq();
        this.troop = value.getTroop();
    }

    public Army(
            Integer hq,
            Integer troop
    ) {
        this.hq = hq;
        this.troop = troop;
    }

    @Override
    public Integer getHq() {
        return this.hq;
    }

    public void setHq(Integer hq) {
        this.hq = hq;
    }

    @Override
    public Integer getTroop() {
        return this.troop;
    }

    public void setTroop(Integer troop) {
        this.troop = troop;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Army (");

        sb.append(hq);
        sb.append(", ").append(troop);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    public void from(IArmy from) {
        setHq(from.getHq());
        setTroop(from.getTroop());
    }


    // TODO: TEST
    @Override
    public boolean equals(Object obj) {
        return EqualsBuilder.reflectionEquals(this, obj);
    }


}
