name: Java Continuous Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: olafurpg/setup-java@v6
      with:
        java-version: openjdk@1.11
    - name: Test with Maven
      run: mvn -B clean test --file pom.xml
